name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1
        
      - name: Init
        run: |
          python3 tools/git-sync-deps
          bin/fetch-ninja
          
      - name: Build
        run: |
          bin/gn gen out/Static --args='is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_system_icu=false skia_use_system_harfbuzz=false'
          ninja -C out/Static
          
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: out/Static/**.lib
